symfony-crud-joabson/src/Entity/TbEnderecos.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TbEnderecosRepository")
 */
class TbEnderecos
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $cod_endereco;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $quadra_endereco;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $numero_endereco;

    private $observacao;

   


    public function getCodEnderecos(): ?int
    {
        return $this->cod_endereco;
    }

    public function getQuadraEnderecos(): ?string
    {
        return $this->quadra_endereco;
    }

    public function setQuadraEnderecos(string $quadra_endereco): self
    {
        $this->quadra_endereco = $quadra_endereco;

        return $this;
    }
    public function setNumeroEndrecos(): ?float
    {
        return $this->numero_endereco;
    }

    public function setNumeroEndrecos(float $numero_endereco): self
    {
        $this->numero_endereco = $numero_endereco;

        return $this;
    }
    public function getObservacao(): ?string
    {
        return $this->observacao;
    }

    public function setObservacao(string $observacao): self
    {
        $this->observacao = $observacao;

        return $this;
    }

  
}

symfony-crud-joabson/src/Form/TbEnderecosType.php
<?php

namespace App\Form;

use App\Entity\TbEnderecos;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class TbEnderecosType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('quadra_endereco', TextType::class, [
                'constraints' => new NotBlank([
                    'message' => 'name.not_blank',
                ])
            ])

            ->add('numero_endereco', TextType::class, [
                'constraints' => new NotBlank([
                    'message' => 'name.not_blank',
                ])
            ])

            ->add('observacao', TextType::class, [
                'constraints' => new NotBlank([
                    'message' => 'name.not_blank',
                ])
            ])
        ;

        $builder->get('numero_endereco')
                ->addModelTransformer(new CallbackTransformer(
                    function ($toInt) {
                        if(!empty($toInt)){
                            return str_replace('.','', $toInt);
                        }
                    },
                    function ($toFloat) {
                        if(!empty($toFloat)){
                            $number = str_replace('.','', $toFloat);
                            $number = str_replace(',','.', $number);
                            return $number;
                        }
                    }
                ))
        ;
    }
}

symfony-crud-joabson/src/Controller/TbEnderecosController.php
<?php

namespace App\Controller;

use App\Entity\TbEnderecos;
use App\Form\TbEnderecosType;
use App\Repository\TbEnderecosRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/tb/enderecos")
 */
class TbEnderecosController extends AbstractController
{
    /**
     * @Route("/", name="tb_enderecos_index", methods={"GET"})
     */
    public function index(TbEnderecosRepository $tbEnderecosRepository): Response
    {
        return $this->render('tb_enderecos/index.html.twig', [
            'tb_enderecos' => $tbEnderecosRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="tb_enderecos_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $tbEnderecos = new TbEnderecos();
        $form = $this->createForm(TbEnderecosType::class, $tbEnderecos);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($tbEnderecos);
            $entityManager->flush();

            return $this->redirectToRoute('tb_enderecos_index');
        }

        return $this->render('tb_enderecos/new.html.twig', [
            'tb_endereco' => $tbEnderecos,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{cod_endereco}", name="tb_enderecos_show", methods={"GET"})
     */
    public function show(TbEnderecos $tbEnderecos): Response
    {
        return $this->render('tb_enderecos/show.html.twig', [
            'tb_endereco' => $tbEnderecos,
        ]);
    }

    /**
     * @Route("/{cod_endereco}/edit", name="tb_enderecos_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, TbEnderecos $tbEnderecos): Response
    {
        $form = $this->createForm(TbEnderecosType::class, $tbEnderecos);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('tb_enderecos_index', [
                'cod_endereco' => $tbEnderecos->getCodEnderecos(),
            ]);
        }

        return $this->render('tb_enderecos/edit.html.twig', [
            'tb_endereco' => $tbEnderecos,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{cod_endereco}", name="tb_enderecos_delete", methods={"DELETE"})
     */
    public function delete(Request $request, TbEnderecos $tbEnderecos): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tbEnderecos->getCodEnderecos(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($tbEnderecos);
            $entityManager->flush();
        }

        return $this->redirectToRoute('tb_enderecos_index');
    }
}

symfony-crud-joabson/templates/tb_enderecos/_delete_form.html.twig
<form method="post" action="{{ path('tb_enderecos_delete', {'cod_endereco': tb_endereco.getCodEnderecos}) }}" onsubmit="return confirm('Tem certeza que deseja deletar esse item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tb_endereco.getCodEnderecos) }}">
    <button class="btn"><i class="delete-icon fa fa-trash" aria-hidden="true" title="Deletar"></i></button>
</form>

symfony-crud-joabson/templates/tb_enderecos/_form.html.twig
{{ form_start(form) }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        {{ form_label(form.quadra_endereco, 'Quadra') }}
                        {{ form_widget(form.quadra_endereco, {'attr': {'class': 'form-control'}, 'required':false}) }}
                        <small class="text-danger">{{ form_errors(form.quadra_endereco) }}</small>
                    </div>
                </div>
             
                <div class="col-12">
                    <div class="form-group">
                        <label>{{ form_label(form.numero_endereco, 'Numero') }}</label>
                        <div class="input-group mb-2">
                            <div class="input-group-prepend">
                            <div class="input-group-text">R$</div>
                            </div>
                            {{ form_widget(form.numero_endereco, {'attr': {'class': 'form-control','data-mask':'000000','data-mask-reverse':'true'}, 'required':false}) }}
                        </div>
                        <small class="text-danger">{{ form_errors(form.numero_endereco) }}</small>
                    </div>
                </div>
               <div class="col-12">
                <div class="form-group">
                    {{ form_label(form.observacao, 'Observacao') }}
                    {{ form_widget(form.observacao, {'attr': {'class': 'form-control'}, 'required':false}) }}
                    <small class="text-danger">{{ form_errors(form.observacao) }}</small>
                </div>
            </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-success">Salvar</button>
    </div>
{{ form_end(form) }}

symfony-crud-joabson/templates/tb_enderecos/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar Enderecos{% endblock %}

{% block breadcrumb %}Enderecos{% endblock %}

{% block body %}
    {{ include('tb_enderecos/_form.html.twig', {'button_label': 'Update'}) }}
{% endblock %}

symfony-crud-joabson/templates/tb_enderecos/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Enderecos{% endblock %}

{% block breadcrumb %}Enderecos{% endblock %}

{% block body %}

    <div class="card">
        <div class="card-header d-flex">
            Enderecos
            <div class="ml-auto">
                <a href="{{ path('tb_enderecos_new') }}">
                    <button type="button" class="btn btn-outline-success">
                        <span class="text-nowrap"><i class="fa fa-plus" aria-hidden="true"></i> Adicionar Enderecos</span>
                    </button>
                </a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Enderecos</th>
                        <th>Quadra</th>
                        <th>Observação</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tb_endereco in tb_enderecos %}
                        <tr>
                            <td>{{ tb_endereco.quadraEnderecos }}</td>
                            <td>{{ tb_endereco.numeroEnderecos|price(2, ',', '.') }}</td>
                            <td>{{ tb_endereco.observacao }}</td>
                            <td>
                                <div class="d-flex">
                                    <a href="{{ path('tb_enderecos_edit', {'cod_endereco': tb_endereco.getCodEnderecos}) }}"><i class="edit-icon fa fa-pencil" aria-hidden="true" title="Editar"></i></a>
                                    {{ include('tb_enderecos/_delete_form.html.twig') }}
                                </div>
                            </td>
                        </tr>
                    {% else %}
                    <tr>
                        <td colspan="5">Nenhum registro encontrado</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

symfony-crud-joabson/templates/tb_enderecos/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adicionar Enderecos{% endblock %}

{% block breadcrumb %}Enderecos{% endblock %}

{% block body %}
    {{ include('tb_enderecos/_form.html.twig') }}
{% endblock %}

symfony-crud-joabson/templates/tb_enderecos/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}TbEnderecos{% endblock %}

{% block body %}
    <h1>TbEnderecos</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Cod_endereco</th>
                <td>{{ tb_endereco.codEnderecos }}</td>
            </tr>
            <tr>
                <th>Quadra_endereco</th>
                <td>{{ tb_endereco.quadraEndereco }}</td>
            </tr>
            <tr>
                <th>Numero_endereco</th>
                <td>{{ tb_endereco.numeroEnderecos }}</td>
            </tr>
            <tr>
                <th>Observacao</th>
                <td>{{ tb_endereco.observacao }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('tb_enderecos_index') }}">back to list</a>

    <a href="{{ path('tb_enderecos_edit', {'cod_endereco': tb_endereco.cod_endereco}) }}">edit</a>

    {{ include('tb_enderecos/_delete_form.html.twig') }}
{% endblock %}